---
language: cpp
env:
  matrix:
  - PLATFORM=linux DEBUG=1

script:
  - $CXX helloworld.cpp -o helloworld
  - ./helloworld

before_install:
  - ./travis-scripts/before-install.sh
compiler:
  - clang
  - gcc
